version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: wowsosecure
      MYSQL_DATABASE: account_service_db
      MYSQL_USER: foo
      MYSQL_PASSWORD: bar
    ports:
      - "3306:3306"
    volumes:
      - ./database-init/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data: